project:
  type: website
  resources:
    - "crab_layers/*"
website:
  title: "Whale Entanglement Indicators"
  favicon: "images/favicon.ico"
  back-to-top-navigation: true
  page-footer:
    border: true
    center:
      - text: "Website Owner"
        href: https://www.integratedecosystemassessment.noaa.gov/regions/california-current
      - text: "NOAA"
        href: https://www.noaa.gov/
      - text: "Privacy Policy"
        href: https://www.noaa.gov/privacy.html
      - text: "Information Quality"
        href: https://www.noaa.gov/organization/information-technology/policy-oversight/information-quality
      - text: "Disclaimer"
        href: https://www.fisheries.noaa.gov/national/about-us/website-policies-and-disclaimers
    right:
      - text: "<img src='/images/logos/doc_logo_black.gif' style='height: 50px; width: auto;'/>"
        href: https://www.commerce.gov/
  search: false
  navbar:
    title: "Whale Entanglement Indicators"
    background: "#276189"
    collapse: false
    search: false
    logo: "images/logo-5.png"
    logo-alt: "California Current Integrated Ecosystem Assessment Website"
    logo-href: "https://www.integratedecosystemassessment.noaa.gov/regions/california-current"
    pinned: true
    align: center

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    grid:
      body-width: 1400px
      margin-width: 20px
      sidebar-width: 150px
    link-external-newwindow: true
    link-external-icon: true



