# Github Actions to read CCIEA Google Drive and update Uploader Status table
# Need to grant read/write permissions for Action to do the commits
# Settings -> Actions -> General -> Workflow permissions
    name: Deploy CCIEA Whale Indices and Maps
# Use the following to update on push
    on:
      push:
        branches: main
      workflow_dispatch:
      schedule:
      # update every day at 12 pm UTC = 5 am PDT
        - cron: '0 12 * * *'
    permissions:
      contents: write  # Allows the token to push HTML to the gh-pages branch

    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Check out repository
            uses: actions/checkout@v4
            # Important: set fetch-depth to 0 so the action can push back to the repo
 #           with:
#              fetch-depth: 0

          - name: Set up R
            uses: r-lib/actions/setup-r@v2
              
          - name: Install packages
            uses: r-lib/actions/setup-r-dependencies@v2
            with:
              cache: always
              packages: |
                any::tidyverse
                any::rmarkdown
                any::knitr
                
          - name: Import data
            run: Rscript update_whale-indices.R

          - name: Set up Quarto
            uses: quarto-dev/quarto-actions/setup@v2
            with:
              tinytex: false

          - name: Commit results
            run: |
              git config --local user.email "actions@github.com"
              git config --local user.name "GitHub Actions"
              git add data/items_dashboard.json
              git add data/indicators.csv
              git commit -m 'Dashboard updated' || echo "No changes to commit"
              git push origin || echo "No changes to commit"
              
          - name: Publish to GitHub Pages (and render)
            uses: quarto-dev/quarto-actions/publish@v2
            with:
              target: gh-pages
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
